### ISSUE TITLE
Move dal to its own package + split in several modules

### ISSUE THREAD

**Issue by nicoxx** [gator-life/gator.life#78]

**Comment by m-mokhtari** [comment]
Create a package "datamodel",
- move each dal class in a separate file
- move frontendstruct.py

In each dal class, create constants for entity kinds/property names

**Comment by nicoxx** [comment]
* _true_ common package (or only directory for now) can be referenced by  anyone, it should not depends on any external package except very common (pytz for date). Probably not Google.cloud on Jsonpickle for example.

* frontendstruct should be with dal in a package (or only directory for now) and renamed when only orchestrator and server depends on it
